### ISSUE TITLE
WebSocketSimpleClient.scala example is not working. It is failing with a long stack trace.

### ISSUE THREAD

**Issue by rohitbishnoi** [zio/zio-http#1410] opened 2022-08-30 10:13 UTC
**Describe the bug**
Getting the following error when I tries to run the https://github.com/dream11/zio-http/blob/main/example/src/main/scala/example/WebSocketSimpleClient.scala example.

```
Aug 30, 2022 3:31:42 PM io.netty.util.concurrent.DefaultPromise safeExecute
SEVERE: Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:499)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at zhttp.service.ChannelFuture.execute$$anonfun$1$$anonfun$1(ChannelFuture.scala:27)
	at zio.internal.FiberRuntime.initiateAsync(FiberRuntime.scala:615)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:905)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1064)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1064)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1064)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:822)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:889)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1064)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:324)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:447)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:217)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:415)
```

**build.sbt content**
```
scalaVersion := "3.1.3"
organization := "dev.zio"
name := "zio-quickstart-hello-world"

libraryDependencies += "dev.zio" %% "zio" % "2.0.0"
libraryDependencies += "io.d11" %% "zhttp" % "2.0.0-RC10"
```

**Comment by gciuloaica** [comment] 2022-08-30 14:37
Duplicate of #1384

**Closed as completed by gciuloaica** 2022-08-30 14:37 UTC
Labels: bug
