### ISSUE TITLE
 Http.fromOptionalHandlerZIO seems to disregard Middleware result

### ISSUE THREAD

**Issue by russwyte** [zio/zio-http#1975] opened 2023-02-02 14:25 UTC
**Describe the bug**
As a developer I expect Middleware to work consistently when applied to an app - but it does not seem to when you use ` Http.fromOptionalHandlerZIO`
**To Reproduce**
Steps to reproduce the behaviour:
```scala
import zio.*
import zio.http.*
import zio.http.model.Method

object Puzzler extends ZIOAppDefault:

  private val authMiddleware =
    Middleware.customAuthZIO(_ =>
      Console.printLine("go no further!!!").orDie
        *> ZIO.succeed(false)
    )

  private val message = Console.printLine("I am proceeding...").orDie

  // This app works as expected...
  private val app =
    Http
      .collectZIO[Request] { case Method.GET -> !! / "text" =>
        message *> ZIO.succeed(Response.text("done."))
      }
      .withDefaultErrorResponse @@ authMiddleware

  // This app always runs the effect even when the auth result is false - why???
  private val app2 = Http.fromOptionalHandlerZIO[Request] { req =>
    message *> ZIO.succeed(Handler.response(Response.text("done.")))
  } @@ authMiddleware

  override val run: URIO[Any, ExitCode] =
    Server
      .serve(app2)
      .provide(
        ServerConfig.live(ServerConfig.default.port(8090)),
        Server.live,
      )
      .exitCode
end Puzzler
```
**Expected behaviour**
I would expect both apps to behave the same in regard to the Middleware.

**Additional context**
Seems to have been introduced in release `0.0.4`
This seems to be the [heart of this issue](https://github.com/softwaremill/tapir/issues/2708)?

**Comment by vigoo** [comment] 2023-02-07 15:17
@russwyte this is by design. 

The auth middlewares (everything which is `HandlerMiddleware`) are applied to handlers. 

In the above example, in `app` we define a `Http` which describes the request-handler routing and the actual request handler (`Handler`) together. The partial function passed to `Http.collectZIO` defines a routing (matching on `GET` and `/text`) and an effectual handler that when gets a request, it prints the message and returns with the given response "done".

So it's two components:

```
[Route to GET /text] 
  => [Handle request: printLine and response(done)]
```

In the `app2` example we define an _effectual routing_ instead. Here the ZIO effect produces the request handler itself, depending on the input. So it would look something like this:

```
[Route calculation: printLine and succeed with a handler (regardless of input)]  
  => [run the produced handler which responds with done]
```

After the middleware refactoring between 0.0.3 and 0.0.4, now we have a very simple and strict rule of how middlewares are applied. As I wrote above, most of the middlewares are handler middlewares and this is visible from their types. A handler middleware is always applied on the handler level and cannot affect the routing. So when applied to both cases, with the previous notation, we would get something like this:

app:
```
[Route to GET /text] 
  => [Authorize, fail with 401] 
  => [otherwise Handle request: printLine and response(done)]
```

app2:
```
[Route calculation: printLine and succeed with a handler (regardless of input)]  
  =>  [Authorize, fail with 401] 
  =>  [otherwise run the produced handler which responds with done]
```

So as you can see here the effect that prints the message is _before_ the middleware's check.

I hope this explanation helps.

**Comment by vigoo** [comment] 2023-02-07 15:20
Closing for now, please reopen if you feel the explanation is not right.

**Comment by vigoo** [comment] 2023-02-07 15:20
(This behavior will be documented in detail for the 1.0 release)

**Closed as completed by vigoo** 2023-02-07 15:20 UTC
Labels: bug

**Comment by russwyte** [comment] 2023-02-07 19:58
Thank you so much for explaining!

**Comment by frekw** [comment] 2023-02-08 09:05
I also ran into this and was very confused before finding this issue.

I think simply renaming it to `Route.fromOptionalHandlerZIO` would have made it much clearer (to me) that the optionality of returning a `Handler` is actully "executing the routing", so to speak. Especially since I have experience with the previous version the top level `Http` behaving like that was very surprising.

**Comment by vigoo** [comment] 2023-02-08 09:15
Thanks for the feedback. There was an intermediate phase when it was actually called `Route` but we decided to rename it back to `Http` to be more like the previous version (as there are many functions that more or less work the same way)
