### ISSUE TITLE
How do you specify a Request match component to match query parameters?

### ISSUE THREAD

**Issue by mtk** [zio/zio-http#1031] opened 2022-02-14 18:49 UTC
if i match with "case req => blah", i can get query params (e.g. "?p1=foo&p2=bar") from req.url.queryParams.  but if i try to match with path components *and* a query (e.g. "case req @ Method.GET -> !! / "foo" / "bar" <query matcher>"), i can not figure out what to specify for the query match.  an all too brief pass over the source suggests there is nothing for that yet?  please advise.

**Comment by tusharmath** [comment] 2022-02-15 09:33
Duplicate of #1016

**Closed as completed** 2022-02-15 19:02 UTC
Labels: enhancement
