### ISSUE TITLE
Can only set one header with same name in http response

### ISSUE THREAD

**Issue by GiGurra** [zio/zio-http#1370] opened 2022-07-26 22:35 UTC
**Describe the bug**
Can only set one header with same name in http response. This is problematic especially for set cookie responses

**To Reproduce**
Steps to reproduce the behaviour:
[someresponse].addHeaders(Headers.apply("a" -> "b", "a" -> "c"))

**Expected behaviour**
should be able to add multiple http headers with same name to http response

**Screenshots**
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1761299/181123879-82fab06a-f0e7-4e0e-8488-31a1302a25a0.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: 103.0.5060.134 (Official Build) (arm64)

**Comment by gciuloaica** [comment] 2022-07-27 06:26
Duplicate of #1354

**Closed as completed by gciuloaica** 2022-07-27 06:26 UTC
Labels: bug
