### ISSUE TITLE
[Port already bound Error] In the example `zio-quickstart-restful-webservice`, Pressing Ctrl-C blocks the port 8080

### ISSUE THREAD

**Issue by vivasvan1** [zio/zio-http#2776] opened 2024-04-17 12:38 UTC
**Describe the bug**
In the example `zio-quickstart-restful-webservice`, Running `sbt`, then `run` and Pressing Ctrl-C blocks the port 8080

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'zio-quickstart-restful-webservice' repo
2. Run `sbt`
3. Type `run` and press enter
4. Press Ctrl+C
5. Now type `run` again and press enter
6. See the Error.

**Expected behaviour**
Server.serve should be able to handle interuptions (like Ctrl+C)

**Screenshots**
![image](https://github.com/zio/zio-http/assets/21074796/36aabaf3-d06a-4ad2-bea3-1c39f27286ea)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser N/A
 - Version 22.04

**Additional context**
n/a

**Comment by kyri-petrou** [comment] 2024-06-07 15:31
@jdegoes @vivasvan1 AFAICT this is the intended behaviour, and it's not related to zio-http but with zio (see [here](https://github.com/zio/zio/blob/16e72493508a97ffec3790f7e84c78c77b4d94d1/core/jvm/src/main/scala/zio/internal/PlatformSpecific.scala#L71-L75)).

The workaround is to add `run / fork := true` in the `build.sbt` file so that the server is shut down

**Comment by varshith257** [comment] 2024-06-22 18:11
/attempt #2776

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx17sca80017jl09h4r7tbrs/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by kyri-petrou** [comment] 2024-06-27 04:28
I'm closing this issue since it's not related to `zio-http`, although it'd be good if someone can create a PR in the `zio-quickstart-restful-webservice` repo as per my comment above

**Closed as completed by kyri-petrou** 2024-06-27 04:28 UTC
Labels: bug, 💎 Bounty, 💰 Rewarded
