### ISSUE TITLE
Sending websocket messages to other connected clients

### ISSUE THREAD

**Issue by frabbit** [zio/zio-http#1340] opened 2022-07-08 20:32 UTC
Hey, and thanks for this great library. I'm currently trying to figure out how to send a message from one client to another one. I cannot find a clean way based on the API. I expected some kind of a connection handle that I can store in a client lookup map inside of a TRef. In order to send a message from Client A to client B, I would use the handle of client B to forward the message from client A. I would be glad to get some input here.

**Comment by frabbit** [comment] 2022-07-08 20:45
To be clear, what I meant was sending messages between clients that are all connected to a websocket server. The server would send a new message to client B after receiving a message of client A.

**Comment by tusharmath** [comment] 2022-07-10 11:43
Hey @frabbit your timing couldn't be better :)
I am already working on #1325 to make the websocket API a lot more ergonomic.

That being said you can still implement the above usecase with ZHub or a Queue

**Comment by tusharmath** [comment] 2022-07-10 11:44
Duplicate of #1314

**Comment by frabbit** [comment] 2022-07-10 12:39
Interesting, I already thought about something like a Queue. This would mean a Queue (Inbox) for every client right? I wonder at which point I would create the stream for each client which pulls from this queue. I would assume that I have to create the stream when the client connects and close when the client disconnects. I'm still wondering how to do this exactly with `Socket.collect[WebSocketFrame]`.

**Comment by frabbit** [comment] 2022-07-10 12:55
Ok, I think I got it. I need two sockets which are merged. The first one handles incoming messages and the second one is listening to the queue. Does this sound reasonable?

**Comment by tusharmath** [comment] 2022-07-11 01:13
Take a look at the documentation here - https://github.com/zio/zio/blob/series/2.x/docs/datatypes/concurrency/hub.md

I think ZHub will perform better than multiple queues

**Comment by frabbit** [comment] 2022-07-11 08:14
Thx a lot, it seems that one central hub and one subscription (with filter by a unique clientId) per client is a good solution.

**Closed as completed** 2022-07-12 02:39 UTC
Labels: duplicate
