### ISSUE TITLE
Generated OpenAPI code does not include authentication information from the endpoint

### ISSUE THREAD

**Issue by countfloyd** [zio/zio-http#3096] opened 2024-09-05 23:48 UTC
If I have an endpoint with a ".auth(AuthType.Bearer)" call in it, the generated OpenAPI code doesn't include any of this authentication information. As a result, one can't call the endpoint from the swagger page because they can't enter the authentication information.

Here is an example endpoint exhibiting this behaviour:

```
val createUserEndpoint: Endpoint[Unit, String, Nothing, String, AuthType.Bearer] =
    Endpoint(RoutePattern.POST / "api" / "auth" / "sync" / "users")
      .in[String]
      .out[String]
      .tag("Users")
      .auth(AuthType.Bearer)
```

When this endpoint is rendered to OpenAPI, there is no "security" information provided. Therefore, it's impossible to call this endpoint (or any auth'ed endpoint, I believe).

**Comment by countfloyd** [comment] 2024-09-05 23:55
It would also be great if we could populate the global "security" section of the OpenAPI object so that one could just provide the security information once for all of the endpoints instead of needing to populate it for each endpoint. Tapir does this.

**Comment by 987Nabil** [comment] 2024-09-06 06:36
Duplicate of #2592

**Closed as completed by 987Nabil** 2024-09-06 06:36 UTC
Labels: bug
